# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetProxOne <- function(y, weights) {
    .Call('_hierbasis2_GetProxOne', PACKAGE = 'hierbasis2', y, weights)
}

FitAdditive <- function(y, weights, ak, x, beta, max_lambda, lam_min_ratio, alpha, tol, p, J, n, nlam, max_iter, beta_is_zero, active_set) {
    .Call('_hierbasis2_FitAdditive', PACKAGE = 'hierbasis2', y, weights, ak, x, beta, max_lambda, lam_min_ratio, alpha, tol, p, J, n, nlam, max_iter, beta_is_zero, active_set)
}

prox <- function(u, w) {
    .Call('_hierbasis2_prox', PACKAGE = 'hierbasis2', u, w)
}

solvehierbasis <- function(design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda) {
    .Call('_hierbasis2_solvehierbasis', PACKAGE = 'hierbasis2', design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda)
}

