# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prox <- function(u, w) {
    .Call('_hierbasis2_prox', PACKAGE = 'hierbasis2', u, w)
}

solvehierbasis <- function(design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda) {
    .Call('_hierbasis2_solvehierbasis', PACKAGE = 'hierbasis2', design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda)
}

